#!/bin/env node

const { writeFileSync } = require("fs");
const { resolve } = require("path");
const { rm, mkdir } = require("shelljs");

const chokidar = require("chokidar");

// Make Mithril happy
if (!global.window) {
	global.window = global.document = global.requestAnimationFrame = undefined;
}

const invalidate = (pred, cache) => {
	for (const key in cache) {
		if (pred(key)) delete cache[key];
	}
};

const getTemplate = () => {
	const markup = resolve(__dirname, "..", "src/markup");
	invalidate(test => !test.startsWith(__dirname), require.cache);
	return require(markup);
};

const debounce = t => f => {
	let timeout;
	return (...args) => {
		clearTimeout(timeout);
		timeout = setTimeout(() => f(...args), t);
	};
};

const tryCatch = f => {
	try {
		f();
	} catch (e) {
		console.error(e);
	}
};

const outDir = resolve(__dirname, "..", "docs");

const bob = ({ watch = true }) => {
	const build = () => (
		console.log("Building src/markup..."),
		tryCatch(() => {
			const { html, stylesheets } = getTemplate();

			// clean outDir
			rm("-rf", resolve(outDir, "css"));
			rm(resolve(outDir, "index.html"));

			// create outDir for CSS
			mkdir("-p", resolve(outDir, "css"));

			writeFileSync(resolve(outDir, "index.html"), html);
			stylesheets.forEach(([path, css]) =>
				writeFileSync(resolve(outDir, path), css),
			);
		})
	);

	if (watch) {
		console.log("Watching src/markup...");
		chokidar
			.watch(resolve(__dirname, "..", "src/markup"))
			.on("all", debounce(100)(build));
	} else build();
};

module.exports = { builder: bob };

if (require.main === module) {
	module.exports({});
}
