#!/usr/bin/env node

const sh = require("shelljs");
const { resolve } = require("path");

const root = resolve(__dirname, "..");
const node_modules = resolve(root, "node_modules");
const vendor = resolve(root, "docs/js/vendor");

const fromModule = s => resolve(node_modules, s);
const toVendor = s => resolve(vendor, s);

sh.mkdir("-p", vendor);

sh.rm("-rf", toVendor("lottie.js"));

sh.cp(fromModule("lottie-web/build/player/lottie.js"), vendor);
